clubcompass/clubcompass.net

pages/api/createUser.js, pages/api/getClubById.js, pages/api/getClubs.js, pages/api/getTags.js, pages/api/getUserInfo.js, pages/api/hello.js, pages/api/signupUser.js, prisma/schema.prisma
Addressing Changes:
- createUser
- getClubByID
- getClub
- getTags
- getUserInfo
- signupUser
- deleted getClubByName
- changed some of the names in the model of schema
- deleted sample hello.js function
closes: #5
=> :sparkles: Added CRUD features (#5)

components/cards/Card.jsx, components/cards/CardContainer.jsx, components/tags/Tag.jsx
- Added bottom spacing on Title of `Card`
- Increased size of Tags on `Card`
- Centered `Card` in `CardContainer`
closes: #11
=> 🪄 Fix Spacing on Card Component (#11)

.gitignore, components/tags/Tag.jsx, config/supabase.js, context/auth.js, context/index.js, package-lock.json, package.json, pages/_app.js, pages/dashboard.jsx, pages/index.jsx, pages/login.jsx, pages/signup.jsx
- Created login, signup, and dashboard pages
- `auth` context
- wrapped `_app` in `Auth.Provider`
- `supabase` for config
- ignored .vscode folder
- removed console.log from Tag
- installed `@supabase/supabase-js`
- added config in .env
closes: #17
=> 💧✨ Authentication with Supabase (#17)

components/cards/Card.jsx, components/cards/Cards.jsx, package-lock.json, package.json, tailwind.config.js
Adressing changes:
- Descriptions that are too long expanding height of `Card`
- `Card` with long title and long dicription didn't fit
Addional changes:
- Installed tailwind line-clamp package:
`npm install @tailwindcss/line-clamp`
- Added tailwind line-clamp dependancy
- Added tailwind line-clamp plugin
closes: #23
=> 💧🪄 Truncate Long Descriptions (#23)

package-lock.json, package.json, pages/api/algolia/uploadClubs.js, pages/api/getAllClubs.js
Adressing changes:
- uploadClubs function in /api/algolia/
- clear null records being returned from getAllClubs function
closes: #21
=> :sparkles: :cloud: clubs to algolia from DB (#21)

components/cards/Card.jsx, package-lock.json, package.json, pages/login.jsx, pages/register.jsx
- Added 6pt margin on mobile
- Full width on mobile
- Increased upper margin on element below button
- Absolute positioning for support section
- Installed algoliasearch
- Added name dependancy in Card
closes: #36
=> 💧🪄 Mobile login and register page tweaks (#36)

components/clubs/Card.jsx, package-lock.json, pages/club/[name].jsx
- Fixes route for Club Pages
- Removes hyphen from Club name
- Capitolizes Club name
- Temporarily commented out `Carousel` due to error
closes #62
=> 🪄 Fix Route and Naming for Club Pages (#62)

lib/db/create.js, lib/db/delete.js, lib/db/get.js, lib/db/update.js
- updated all `update` methods
- renamed `update` to `u`
- get takes in id in inital param rather than using other objects
- update route helpers to first letter
closes: #66
=> 🛠 Update all existing update methods (#66)

components/general/ToolTip.jsx
- Created resuable `ToolTip` component
- Created general components folder
closes #71
=> ✨ Create ToolTip Component

components/general/CopyText.jsx
- Created resuable `CopyText` component
closes #70
=> ✨ Create CopyText Component

pages/api/create/club.js, pages/api/get/clubBySlug.js, prisma/schema.prisma
Adressing changes:
- schema.prisma
- create club function
- added get club by slug function
closes #77
=> 🪄 Added support for slugs in schema (#77)

package-lock.json, package.json, pages/api/get/club.js
- club.js rewrote query
closes: #89
=> 🏥 Fixed getting clubs by tag (#89)

components/clubs/Card.jsx
=> 🪄 Set all card heights to 223px (#120)

package.json, seed_script/clubs.json, seed_script/seed.js, seed_script/users.json
- seed.js script seeds database, uncomment what u want to seed in main()
- added command to package.json
- users and clubs.json hold data
closes: #68
=> 🚨 Seeding database script (#68)

pages/api/_middleware.js
- added middleware.js file
- middleware file uses API_AUTHENTICATION_KEY env var
- middleware reads secret_key through headers
closes: #88
=> 🔒 Middleware and env vars to secure api (#88)

pages/api/create/user.js, pages/api/get/user.js, prisma/schema.prisma, seed_script/seed.js, seed_script/users.json
- get and create user routes
- modified schema to include grade and interests relation
- modified seed.js
- modified users.json
closes: #192
=> 🛠 Update user schema add grades+interests (#192)

lib/db/club.js, pages/api/club/links/add.js, pages/api/club/links/delete.js, pages/api/club/links/get.js, pages/api/club/links/remove.js
Addressing changes: 
- added link routes to api
- added link functions to db driver
closes: #229
=> ✨ Link support (#229)

components/general/Loading.jsx, components/general/input/TagSelection.jsx, components/pages/club/ClubSimilarClubs.jsx, pages/clubs.jsx
- Created `Loading` component
- Replaced all current "Loading..." with new `Loading` component
closes: #228
=> 🪄 Loading Animation (#228)

seed_script/clubs.json, seed_script/seed.js
- rewritten to use new functions
- seeds: tags, users, clubs, club statuses, club links, club members
closes: #233
=> 🌱 Seed script rewrite (#233)

lib/database.js, lib/db/index.js, lib/db/invite.js, pages/api/club/get.js, pages/api/invite/accept.js, pages/api/invite/create.js, pages/api/invite/decline.js, pages/api/invite/delete.js, pages/api/user/get.js, prisma/schema.prisma
- create, accept, decline, and delete functions for invites
- added functions in db driver
- updated get user and get club functions to fetch invites
closes: #237
=> ✨ Added support for invites (#237)

lib/db/club.js, pages/api/club/update/availability.js, prisma/schema.prisma
- modified schema
- added api route
- updated driver
closes: #240
=> ✨ Support for club availability (#240)

components/general/Loading.jsx
Make loading component more universal
closes: #245
=> 🔀 Master -> loading-height-245

lib/db/role.js, pages/api/role/create.js, prisma/schema.prisma
- modified create role api route and db driver function
- modified schema
closes: #249
=> ✨ Added support for role descriptions (#249)

lib/db/user.js, pages/api/user/create.js, pages/api/user/get.js, prisma/schema.prisma
- modified create and get user functions
- modified schema
- modified get user in db driver
- fixed issue with fetching user invites in get user functions
closes: #247
=> ✨ Support for club compass id (#247)
